### ISSUE TITLE
I do have problem while tryng chaining graphql_handler function to Router

### ISSUE THREAD

**Issue by ayratmsk** [oliverjumpertz/axum-graphql#2]
Just before testing graphql_playground with axum server [main.rs]
```
...

#[tokio::main]
async fn main() {
    let schema = Schema::build(QueryRoot, EmptyMutation, EmptySubscription).finish();

    let app = Router::new()
        .route("/", get(graphql_playground).post(graphql_handler))
        .route("/health", get(health))
        .layer(Extension(schema)); // (1)

...
}
```

I got compile error:
```
error[E0277]: the trait bound `fn(GraphQLRequest, axum::Extension<async_graphql::Schema<QueryRoot, EmptyMutation, EmptySubscription>>) -> impl std::future::Future<Output = GraphQLResponse> {graphql_handler}: Handler<_, _, _>` is not satisfied
   --> src/main.rs:15:50
    |
15  |         .route("/", get(graphql_playground).post(graphql_handler))
    |                                             ---- ^^^^^^^^^^^^^^^ the trait `Handler<_, _, _>` is not implemented for fn item `fn(GraphQLRequest, axum::Extension<async_graphql::Schema<QueryRoot, EmptyMutation, EmptySubscription>>) -> impl std::future::Future<Output = GraphQLResponse> {graphql_handler}`
    |                                             |
    |                                             required by a bound introduced by this call
```

Can you pls explain?

**Comment by ayratmsk** [comment]
It was an errata in tutorial: https://oliverjumpertz.com/blog/how-to-build-a-powerful-graphql-api-with-rust/

Consuming GraphqlRequest argument **req** in the fn graphql_handler() was occasionally mentioned first:
<img width="573" alt="изображение" src="https://github.com/oliverjumpertz/axum-graphql/assets/95551107/abdce13b-e5ef-4ee1-a02a-7063ef08996b">

Easy to fix it!
PS: Many tnx for tutorial, btw!

**Comment by oliverjumpertz** [comment]
Hey, happy you figured it out! :) Closing this then.

**Comment by robgero** [comment]
@ayratmsk I don't understand. I am having the same issue. What did you do to fix it?

**Comment by ayratmsk** [comment]
> @ayratmsk I don't understand. I am having the same issue. What did you do to fix it?

Check async graphql_handler() signature! 
You should place "Extension(schema): Extension<ServiceSchema>" parameter first, because "req: GraphQLRequest" is consuming one.

**Comment by oliverjumpertz** [comment]
> @ayratmsk I don't understand. I am having the same issue. What did you do to fix it?

What basically happens is that after you place the actual Axum request, you can add no more extractors (Extension is a so-called extractor). I have just fixed the order in the article. I had forgotten to push that!

**Comment by robgero** [comment]
> Check async graphql_handler() signature!
> You should place "Extension(schema): Extension" parameter first, because "req: GraphQLRequest" is consuming one.

Thanks @ayratmsk 

Great tutorial by the way @oliverjumpertz - look forward to seeing more rust ones :)
